/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['common.js']) {
  _$jscoverage['common.js'] = [];
  _$jscoverage['common.js'][1] = 0;
  _$jscoverage['common.js'][9] = 0;
  _$jscoverage['common.js'][80] = 0;
  _$jscoverage['common.js'][83] = 0;
}
_$jscoverage['common.js'][1]++;
Common = {util: require("util"), fs: require("fs"), path: require("path"), tools: require("./utilities")};
_$jscoverage['common.js'][9]++;
Common.twitterStreamKeywords = ["eltiempo", "el_tiempo", "#tiempo", "meteo", "meteorologia", "meteorologico", "precipitaciones", "atmosfera", "atmosferico", "atmosferica", "temperatura", "humedad", "cirros", "cumulos", "chubascos", "\"frente frio\"", "\"ola de calor\"", "\"ola de frio\"", "\"gota fria\"", "\"bajo cero\"", "\"\u00c2\u00ba C\"", "\u00c2\u00baC", "hPa", "l/m2", "litros metro", "precipitacion", "lluvias", "nieve", "viento", "llueve", "lloviendo", "llover", "aguacero", "diluviando", "chubasco", "nevar", "nevando", "nieva", "nublado", "tormenta", "truenos", "truena", "tronando", "pedrisco", "soleado", "niebla", "helada", "helar", "helando", "aguanieve", "granizo", "granizada", "granizando", "nublando", "huracan", "tornado", "meteorologica", "prevision meteorologica"];
_$jscoverage['common.js'][80]++;
Common.twitterSearchKeywords = Common.twitterStreamKeywords.slice(0, 30);
_$jscoverage['common.js'][83]++;
module.exports = Common;
_$jscoverage['common.js'].source = ["Common = {","  util: require('util'),","  fs:   require('fs'),","  path: require('path'),","  tools: require('./utilities')","};","","","Common.twitterStreamKeywords = [  ","'eltiempo',","'el_tiempo',","'#tiempo',","'meteo',","'meteorologia',","'meteorologico',","'precipitaciones',","'atmosfera',","'atmosferico',","'atmosferica',","//'weather',","'temperatura',","'humedad',","'cirros',","'cumulos',","'chubascos',","'\"frente frio\"',","'\"ola de calor\"',","'\"ola de frio\"',","'\"gota fria\"',","'\"bajo cero\"',","'\"&#194;&#186; C\"',","'&#194;&#186;C',","\"hPa\",","'l/m2',","'litros metro',","'precipitacion',","//'lluvia',","'lluvias',","'nieve',","'viento',","'llueve',","'lloviendo',","'llover',","'aguacero',","'diluviando',","'chubasco',","'nevar',","'nevando',","'nieva',","//'nubes',","'nublado',","'tormenta',","'truenos',","'truena',","'tronando',","'pedrisco',","'soleado',","//'\"sale el sol\"',","//'\"saliendo el sol\"',","//'calor',","//'frio',","'niebla',","'helada',","'helar',","'helando',","//'refrescar',","//'refrescando',","'aguanieve',","'granizo',","'granizada',","'granizando',","'nublando',","'huracan',","'tornado',","'meteorologica',","'prevision meteorologica'","];",""," ","Common.twitterSearchKeywords = Common.twitterStreamKeywords.slice(0,30);\t","//Common.twitterSearchKeywords = Common.twitterSearchKeywords.splice(0,25);","","module.exports = Common;"];
