/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['router.js']) {
  _$jscoverage['router.js'] = [];
  _$jscoverage['router.js'][1] = 0;
  _$jscoverage['router.js'][4] = 0;
  _$jscoverage['router.js'][6] = 0;
  _$jscoverage['router.js'][7] = 0;
  _$jscoverage['router.js'][8] = 0;
  _$jscoverage['router.js'][12] = 0;
  _$jscoverage['router.js'][13] = 0;
  _$jscoverage['router.js'][14] = 0;
  _$jscoverage['router.js'][24] = 0;
  _$jscoverage['router.js'][25] = 0;
  _$jscoverage['router.js'][26] = 0;
  _$jscoverage['router.js'][27] = 0;
}
_$jscoverage['router.js'][1]++;
var PlaceRoutes = require("./controllers/routes/placeroutes");
_$jscoverage['router.js'][4]++;
var Router = (function (app) {
  _$jscoverage['router.js'][6]++;
  this.setRoutes = (function () {
  _$jscoverage['router.js'][7]++;
  _setSiteIndexRoute();
  _$jscoverage['router.js'][8]++;
  PlaceRoutes.createRoutes(app, "places");
});
  _$jscoverage['router.js'][12]++;
  var _setSiteIndexRoute = (function () {
  _$jscoverage['router.js'][13]++;
  app.get("/", (function (req, res) {
  _$jscoverage['router.js'][14]++;
  res.render("index", {title: "Social Weather", scripts: ["javascripts/browserlocator.js", "/javascripts/index.js"]});
}));
});
});
_$jscoverage['router.js'][24]++;
module.exports.createRoutes = (function (app) {
  _$jscoverage['router.js'][25]++;
  var router = new Router(app);
  _$jscoverage['router.js'][26]++;
  router.setRoutes();
  _$jscoverage['router.js'][27]++;
  return router;
});
_$jscoverage['router.js'].source = ["var PlaceRoutes = require('./controllers/routes/placeroutes');","","","var Router = function(app) {","\t","\tthis.setRoutes = function() {\t","\t\t_setSiteIndexRoute();\t\t","\t\tPlaceRoutes.createRoutes(app, 'places');","\t}\t\t","","","\tvar _setSiteIndexRoute = function() {","\t\tapp.get('/', function(req, res){","\t\t  res.render('index', { title: 'Social Weather' , ","\t\t\t\t\t\t\t\tscripts: ['javascripts/browserlocator.js',","\t\t\t\t\t\t\t\t\t\t\t//'/javascripts/jquery.min.js',","\t\t\t\t\t\t\t\t\t\t\t'/javascripts/index.js']}","\t\t\t\t\t);","\t\t});","\t};\t\t","};","","","module.exports.createRoutes = function(app){","\tvar router = new Router(app);","\trouter.setRoutes();","\treturn router;","}"];
