/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['utilities.js']) {
  _$jscoverage['utilities.js'] = [];
  _$jscoverage['utilities.js'][1] = 0;
  _$jscoverage['utilities.js'][2] = 0;
  _$jscoverage['utilities.js'][3] = 0;
  _$jscoverage['utilities.js'][7] = 0;
  _$jscoverage['utilities.js'][8] = 0;
  _$jscoverage['utilities.js'][9] = 0;
}
_$jscoverage['utilities.js'][1]++;
module.exports.bind = (function (fn, scope) {
  _$jscoverage['utilities.js'][2]++;
  return (function () {
  _$jscoverage['utilities.js'][3]++;
  return fn.apply(scope, arguments);
});
});
_$jscoverage['utilities.js'][7]++;
module.exports.stringContains = (function (str, substr) {
  _$jscoverage['utilities.js'][8]++;
  if (substr.length == 0) {
    _$jscoverage['utilities.js'][8]++;
    return false;
  }
  _$jscoverage['utilities.js'][9]++;
  return str.indexOf(substr) != -1;
});
_$jscoverage['utilities.js'].source = ["module.exports.bind = function(fn, scope) {","  return function () {","    return fn.apply(scope, arguments);","  }","}","","module.exports.stringContains = function(str, substr) { ","\tif(substr.length == 0) return false;","\treturn str.indexOf(substr) != -1; ","}"];
