Common = {
  util: require('util'),
  fs:   require('fs'),
  path: require('path'),
  tools: require('./utilities')
};


Common.twitterStreamKeywords = [
'#eltiempo',
'el_tiempo',
'#tiempo',
'meteo',
'meteorologia',
'meteorologico',
'precipitaciones',
'atmosferico',
'atmosferica',
'weather',
'temperatura',
'humedad',
'cirros',
'cumulos',
'chubascos',
'"frente frio"',
'"ola de calor"',
'"ola de frio"',
'"gota fria"',
'"bajo cero"',
'"º C"',
'ºC',
"hPa",
'l/m2',
'"litros metro"',
'precipitacion',
'"esta lloviendo"',
'"esta nevando"',
'"esta nublado"',
'lluvias',
'nieve',
'viento',
'llueve',
'lloviendo',
'llover',
'aguacero',
'diluviando',
'chubasco',
'nevar',
'nevando',
'nieva',
'nuboso',
'nublado',
'tormenta',
'truenos',
'truena',
'tronando',
'pedrisco',
'soleado',
'"sale el sol"',
'"saliendo el sol"',
'niebla',
'helada',
'helar',
'helando',
'"tiempo de mierda"',
'"buen tiempo hace"',
'"mal tiempo hace"',
'"hace buen tiempo"',
'"hace mal tiempo"',
'aguanieve',
'granizo',
'granizada',
'granizando',
'nublando',
'huracan',
'tornado',
'meteorologica',
'"prevision meteorologica"',
'picazomario',
'aemet',
'"radar lluvia"',
'"rain radar"'
];

 
Common.twitterSearchKeywords = [ 
	'eltiempo',
	'el_tiempo',
	'#tiempo',
	'meteo',
	'aemet',
	'meteorologico',
	'precipitaciones',
	'atmosferico',
	'atmosferica',
	'temperatura',
	'humedad',
	'chubascos',	
	'"º C"',
	'ºC',
	"hPa",
	'precipitacion',
	'precipitaciones',
	'"frente frio"',
	'"ola de calor"',
	'"ola de frio"',
	'"bajo cero"',	
	'l/m2',
	'"prevision meteorologica"',
	'lluvioso',
	'lluviosa',
	'"radar lluvia"',
	'"rain radar"'
];

module.exports = Common;