/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['controllers/placecontroller.js']) {
  _$jscoverage['controllers/placecontroller.js'] = [];
  _$jscoverage['controllers/placecontroller.js'][1] = 0;
  _$jscoverage['controllers/placecontroller.js'][2] = 0;
  _$jscoverage['controllers/placecontroller.js'][6] = 0;
  _$jscoverage['controllers/placecontroller.js'][7] = 0;
  _$jscoverage['controllers/placecontroller.js'][19] = 0;
}
_$jscoverage['controllers/placecontroller.js'][1]++;
var PlaceController = (function (app) {
  _$jscoverage['controllers/placecontroller.js'][2]++;
  this.socketManager = app.socketManager;
});
_$jscoverage['controllers/placecontroller.js'][6]++;
PlaceController.prototype.actionSearch = (function (placeName, response) {
  _$jscoverage['controllers/placecontroller.js'][7]++;
  response.render("place/show", {title: process.env.APP_NAME + " | Buscar " + placeName, locals: {place: placeName, scripts: ["/socket.io/socket.io.js", "/javascripts/jquery.min.js", "/javascripts/dateformater.js", "/javascripts/place.js"]}});
});
_$jscoverage['controllers/placecontroller.js'][19]++;
module.exports = PlaceController;
_$jscoverage['controllers/placecontroller.js'].source = ["var PlaceController = function(app) {","\tthis.socketManager = app.socketManager;\t","};","","","PlaceController.prototype.actionSearch = function(placeName, response) {\t","\tresponse.render('place/show',","\t{\t\t","\t\ttitle:  process.env.APP_NAME + ' | Buscar ' + placeName, ","\t\tlocals: { \tplace: placeName,    ","\t\t\t\t\tscripts: [\t'/socket.io/socket.io.js', ","\t\t\t\t\t\t\t  \t'/javascripts/jquery.min.js',","\t\t\t\t\t\t\t\t'/javascripts/dateformater.js',","\t\t\t\t\t\t\t  \t'/javascripts/place.js']","\t\t\t\t}","\t});\t","};","","module.exports = PlaceController;"];
