/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['controllers/routes/entityroutes.js']) {
  _$jscoverage['controllers/routes/entityroutes.js'] = [];
  _$jscoverage['controllers/routes/entityroutes.js'][1] = 0;
  _$jscoverage['controllers/routes/entityroutes.js'][2] = 0;
  _$jscoverage['controllers/routes/entityroutes.js'][3] = 0;
  _$jscoverage['controllers/routes/entityroutes.js'][6] = 0;
  _$jscoverage['controllers/routes/entityroutes.js'][10] = 0;
}
_$jscoverage['controllers/routes/entityroutes.js'][1]++;
var EntityRoutes = (function (app, root) {
  _$jscoverage['controllers/routes/entityroutes.js'][2]++;
  this.rootWord = root;
  _$jscoverage['controllers/routes/entityroutes.js'][3]++;
  this.app = app;
});
_$jscoverage['controllers/routes/entityroutes.js'][6]++;
EntityRoutes.prototype.setRoutes = (function () {
});
_$jscoverage['controllers/routes/entityroutes.js'][10]++;
module.exports = EntityRoutes;
_$jscoverage['controllers/routes/entityroutes.js'].source = ["var EntityRoutes = function(app, root) {","\tthis.rootWord = root;","\tthis.app = app;","}","\t","EntityRoutes.prototype.setRoutes = function() {\t","}","\t","\t","module.exports = EntityRoutes;"];
