/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['controllers/routes/placeroutes.js']) {
  _$jscoverage['controllers/routes/placeroutes.js'] = [];
  _$jscoverage['controllers/routes/placeroutes.js'][1] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][2] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][6] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][7] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][8] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][11] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][14] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][15] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][16] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][19] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][20] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][21] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][22] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][25] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][26] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][27] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][31] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][32] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][36] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][37] = 0;
  _$jscoverage['controllers/routes/placeroutes.js'][41] = 0;
}
_$jscoverage['controllers/routes/placeroutes.js'][1]++;
var PlaceController = require("../placecontroller");
_$jscoverage['controllers/routes/placeroutes.js'][2]++;
var EntityRoutes = require("./entityroutes");
_$jscoverage['controllers/routes/placeroutes.js'][6]++;
var PlaceRoutes = (function (app, root) {
  _$jscoverage['controllers/routes/placeroutes.js'][7]++;
  EntityRoutes.call(this, app, root);
  _$jscoverage['controllers/routes/placeroutes.js'][8]++;
  this.controller = new PlaceController(app);
});
_$jscoverage['controllers/routes/placeroutes.js'][11]++;
PlaceRoutes.prototype = Object.create(EntityRoutes.prototype);
_$jscoverage['controllers/routes/placeroutes.js'][14]++;
PlaceRoutes.prototype.setRoutes = (function () {
  _$jscoverage['controllers/routes/placeroutes.js'][15]++;
  EntityRoutes.prototype.setRoutes.call(this);
  _$jscoverage['controllers/routes/placeroutes.js'][16]++;
  this._search();
});
_$jscoverage['controllers/routes/placeroutes.js'][19]++;
EntityRoutes.prototype._search = (function () {
  _$jscoverage['controllers/routes/placeroutes.js'][20]++;
  var controller = this.controller;
  _$jscoverage['controllers/routes/placeroutes.js'][21]++;
  this.app.post(this._searchPath(), (function (req, res) {
  _$jscoverage['controllers/routes/placeroutes.js'][22]++;
  controller.actionSearch(req.body.place.search_string, res);
}));
  _$jscoverage['controllers/routes/placeroutes.js'][25]++;
  var controller = this.controller;
  _$jscoverage['controllers/routes/placeroutes.js'][26]++;
  this.app.get(this._searchPath() + "/:name", (function (req, res) {
  _$jscoverage['controllers/routes/placeroutes.js'][27]++;
  controller.actionSearch(req.params.name, res);
}));
});
_$jscoverage['controllers/routes/placeroutes.js'][31]++;
EntityRoutes.prototype._searchPath = (function () {
  _$jscoverage['controllers/routes/placeroutes.js'][32]++;
  return "/" + this.rootWord + "/search";
});
_$jscoverage['controllers/routes/placeroutes.js'][36]++;
PlaceRoutes.createRoutes = (function (app, rootWord) {
  _$jscoverage['controllers/routes/placeroutes.js'][37]++;
  new PlaceRoutes(app, rootWord).setRoutes();
});
_$jscoverage['controllers/routes/placeroutes.js'][41]++;
module.exports = PlaceRoutes;
_$jscoverage['controllers/routes/placeroutes.js'].source = ["var PlaceController = require('../placecontroller');","var EntityRoutes = require('./entityroutes');","","","","var PlaceRoutes = function(app, root) {","\tEntityRoutes.call(this, app, root); //super constructor","\tthis.controller = new PlaceController(app);","};","","PlaceRoutes.prototype = Object.create(EntityRoutes.prototype);","","","PlaceRoutes.prototype.setRoutes = function() {\t","\tEntityRoutes.prototype.setRoutes.call(this);","\tthis._search();","}","","EntityRoutes.prototype._search = function() {","\tvar controller = this.controller;\t","\tthis.app.post(this._searchPath(),function (req, res) {","\t\tcontroller.actionSearch(req.body.place.search_string,res);","\t});","\t","\tvar controller = this.controller;\t","\tthis.app.get(this._searchPath() + '/:name',function (req, res) {","\t\tcontroller.actionSearch(req.params.name,res);","\t});\t\t","}","","EntityRoutes.prototype._searchPath = function() {","\treturn '/' + this.rootWord + '/search';","};","","","PlaceRoutes.createRoutes = function(app, rootWord) {","\tnew PlaceRoutes(app,rootWord).setRoutes();","};","\t","\t","module.exports = PlaceRoutes;"];
