/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['models/entity.js']) {
  _$jscoverage['models/entity.js'] = [];
  _$jscoverage['models/entity.js'][1] = 0;
  _$jscoverage['models/entity.js'][5] = 0;
  _$jscoverage['models/entity.js'][9] = 0;
}
_$jscoverage['models/entity.js'][1]++;
var mongoose = require("mongoose");
_$jscoverage['models/entity.js'][5]++;
var Entity = (function () {
});
_$jscoverage['models/entity.js'][9]++;
module.exports = Entity;
_$jscoverage['models/entity.js'].source = ["var mongoose = require('mongoose');","","","//Class DbEntity","var Entity = function() {\t","\t\t","};","","module.exports = Entity;"];
